name: Build - Test - Benchmark

on: [push, pull_request]

jobs:
  test-and-bench:
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@v4
        with:
          cmakeVersion: 4.0

      - name: Install CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.20
        with:
          cuda: '12.5.0'

      - name: Install oneMKL and oneTBB
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            intel-oneapi-mkl-devel \
            intel-oneapi-tbb-devel

      - name: Configure (CMake)
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --parallel

      - name: Run unit tests
        run: ctest --test-dir build --output-on-failure

#      - name: Run benchmarks
#        run: |
#          ./build/benchmarks \
#            --benchmark_out=bench.json \
#            --benchmark_out_format=json \
#            --benchmark_repetitions=8 \
#            --benchmark_display_aggregates_only=true

#      - name: Upload benchmark report
#        uses: actions/upload-artifact@v4
#        with:
#          name: benchmark-results
#          path: bench.json